# Generated by Django 5.0.4 on 2024-04-16 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Category', models.CharField(choices=[('Electronics', 'Option 1'), ('Clothing', 'Option 2'), ('Furniture', 'Option 3')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionType', models.CharField(choices=[('IN', 'Incoming stock'), ('OUT', 'Outgoing stock')], max_length=3)),
                ('Quantity', models.IntegerField()),
                ('TransactionDate', models.DateField(auto_now=True)),
                ('Category', models.CharField(choices=[('Electronics', 'Option 1'), ('Clothing', 'Option 2'), ('Furniture', 'Option 3')], max_length=50)),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.products')),
            ],
        ),
    ]
