# Generated by Django 5.0.4 on 2024-04-16 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='productName',
            new_name='product_name',
        ),
    ]
