# Generated by Django 5.0.4 on 2024-04-16 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_productname_products_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactions_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionType', models.CharField(choices=[('IN', 'Incoming stock'), ('OUT', 'Outgoing stock')], max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='transactions',
            name='TransactionType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transactions_type'),
        ),
    ]
