# Generated by Django 5.0.4 on 2024-04-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_transactions_type_alter_transactions_transactiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='TransactionType',
            field=models.CharField(choices=[('IN', 'Incoming stock'), ('OUT', 'Outgoing stock')], max_length=3),
        ),
        migrations.DeleteModel(
            name='transactions_type',
        ),
    ]
